# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'LeeDropDownMenuDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LeeDropDownMenuDemo
  pod 'Reveal-SDK', :configurations => ['Debug']

  target 'LeeDropDownMenuDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LeeDropDownMenuDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
